version: 2
jobs:
  build:
    machine: true
    shell: sudo /bin/bash
    steps:
      - run: exit 1
      - run: docker version
      - run: docker-compose version


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
