version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: rustc --version
      - run: cargo --version
  test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: rustc --version
      - run: cargo --version
workflows:
  version: 2
  btd:
    jobs:
      - build
      - test
