version: 2.0
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - run: circleci step halt
      - run: ls -la /bin

notify:
  webhooks:
    - url: https://www.example.com/circleci/notify
  branches:
    only:
      - /.*/
