version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -eo pipefail

    steps:

      # Get the code from the VCS provider.
      - checkout
      - run: ls -l /usr/bin/python*
      - run: python --version
      - run: python2.6 --version || python2.7 --version || true
      - run: python3 --version


workflows:
  version: 2
  build:
    jobs:
      - build-and-test
