version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - scheduled
    jobs:
      - build
