version: 2
jobs:
  build:
    docker:
      - image: node:9
    steps:
      - checkout
      # Versions Check
      - run:
          name: Node version
          command: node -v
      - run:
          name: Yarn version
          command: yarn --version
