version: 2
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: mkdir -p artifacts
      - run: cp junit.xml artifacts/
      - store_artifacts:
          path: artifacts
      - store_test_results: 
          path: artifacts
