version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7-stretch-node
    steps:
      - run: mkdir -p foo && touch foo/bar
      - save_cache:
          key: shenanigans
          paths:
            - foo      
      - run: sleep 10
      - run: rm -rf foo
      - restore_cache:
          key: shenanigans
