version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7
    steps:
      - run:
          command: >
            echo '
            <?php 
            echo "hello world" 
            ?>
            ' | php
