version: 2.0
jobs:
  nontest:
    machine: true
    working_directory: ~/project
    steps:
      - run: echo "Hello"
      - run: circleci step halt
      - run: echo "Hola"
      - run:
          name: Say Goodbye
          command: echo "Hello Goodbye"

workflows:
  version: 2
  build:
    jobs:
      - nontest:
          tags:
            only: /foo-.*/
