version: 2
jobs:
  build:
    machine: true
    shell: sudo /bin/bash
    steps:
      - run: cat /etc/apt/apt.conf.d/10periodic
      - run: cat /etc/*release*


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
