version: 2
jobs:
  build:
    docker:
      - image: node:9
    steps:
      - run: ssh -L 22:github.com:22 git@github.com
      - run: echo "127.0.0.1 github.com" | sudo tee -a /etc/hosts
      - checkout
