version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "hello world"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,49,50,52,54,56,58 * * * *"
          filters:
            branches:
              only:
                - scheduled
    jobs:
      - build
