version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - restore_cache:
          key: v1-source-{{ .Branch }}-{{ .Revision }}
          keys:
            - v1-source-{{ .Branch }}
            - v1-source-
      - checkout
      - save_cache:
          key: v1-source-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
      - run: echo $CIRCLE_TAG



deployment:
  fake_deploy_for_cci2:
    tag: /.*/
    commands:
      - echo "make tags run in 2.0"
