standard_config: &standard_config
  resource_class: xlarge
  docker:
    - image: docker
  environment:
    foobar: nop
  parallelism: 1

version: 2
jobs:
  build:
    <<: *standard_config
    steps:
      - run: echo $foobar
      - run:
          shell: /usr/bin/python
          command: |
            print("does this work?")
