version: 2
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: mkdir -p reports/jest
      - run: cp junit.xml reports/jest/
      - store_artifacts:
          path: reports
      - store_test_results: 
          path: reports
