version: 2
jobs:
  build:
    docker:
        - image: circleci/node:6.11.3-stretch
    steps:
      - run:
          command: >
            echo '
            <?php 
            echo "hello world" 
            ?>
            ' | php
