version: 2
jobs:
  build:
    machine: true
    shell: sudo /bin/bash
    steps:
      - checkout
      - run: docker build -t foo .
      - run:
          when: always
          command: docker info


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
