version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run: docker pull circleci/ruby:2.3.7-jessie
      - run: docker build -t $DOCKER_USER/fooimage:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_USER/fooimage:$CIRCLE_SHA1
  test:
    docker:
      - image: rohara/fooimage:$CIRCLE_SHA1
    parallelism: 3
    steps:
      - run: ruby --version

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - staging
    jobs:
      - build