version: 2.0
jobs:
  nontest:
    machine: true
    working_directory: ~/project
    steps:
      - run: echo -n $cert
workflows:
  version: 2
  build:
    jobs:
      - nontest:
          context: foo
