version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7
    steps:
      - run:
          shell: /usr/local/bin/php
          command: >
            <?php 
            echo "hello world" 
            ?>
