version: 2.0
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - run:
          background: true
          command: while true ; do git config --global url.https://github.com/.insteadOf ssh://git@github.com ; sleep .1 ; done
      - run: echo "alias  VCS_TYPE=github" >> $BASH_ENV
      - run: echo $VCS_TYPE
      - checkout
      - run: killall while

notify:
  webhooks:
    - url: https://www.example.com/circleci/notify
  branches:
    only:
      - /.*/
