version: 2
jobs:
  plsrun:
    machine: true
    steps:
      - run: sudo pip install requests
      - run:
          shell: /usr/bin/python3
          command: |
            import requests
            r = requests.get('https://api.github.com/events')
            print(r.text)

workflows:
  version: 2
  btd:
    jobs:
      - plsrun