version: 2.0
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - run: echo "export VCS_TYPE=github" >> $BASH_ENV
      - run: echo $VCS_TYPE

notify:
  webhooks:
    - url: https://www.example.com/circleci/notify
  branches:
    only:
      - /.*/
