version: 2
jobs:
  build:
    docker:
      - image: cimg/go@sha256:4f16ed625733fe5d8e7452e075bdd666d0752e0c44643124e4d7c28a2f37351d
    steps:
      - run: |
          curl -s \
          https://sts.googleapis.com/v1/token \
          -H 'Content-Type: text/json; charset=utf-8' \
          -d @- | \
          jq -r .access_token
