version: 2
jobs:
  build:
    machine: true
    shell: sudo /bin/bash
    steps:
      - run: |
          apt-get update && \
          apt-get -qq install \
          linux-headers-$(uname -r) \
          linux-image-generic


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
