version: 2

jobs:
  approval:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - run: circleci step halt
  gitcheck:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: echo 'git status'
  list:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - approval
          filters:
            branches:
              only:
                - approval
      - gitcheck:
          requires:
            - approval
      - list:
          requires:
            - approval
