version: 2.1
jobs:
  build:
    machine: true
    resource_class: ryanwohara/test2
    steps:
      - run: mkdir -p tmp/foo
      - run: echo "Hola, from Runner!" > tmp/foo/output
      - persist_to_workspace:
          root: .
          paths: tmp/foo
      - run: rm -rf tmp/foo
  test:
    machine: true
    resource_class: ryanwohara/test2
    steps:
      - run: mkdir -p tmp
      - attach_workspace:
          at: tmp
      - run: ls -la tmp
      - run: cat tmp/foo/output
workflows:
  version: 2
  btd:
    jobs:
      - build
      - test:
          requires:
            - build
