version: 2
jobs:
  build:
    machine: true
    shell: sudo /bin/bash
    steps:
      - run: apt-get update
      - run: apt-get install -y wget

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
