version: 2.0
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/php:7.3-cli
      - shell: /bin/bash -c "/usr/local/bin/php" "-r"
    steps:
      - run: "echo('yay'); echo(\" this probably isn't worth it\");"

notify:
  webhooks:
    - url: https://www.example.com/circleci/notify
  branches:
    only:
      - /.*/
