version: 2
jobs:
  plsrun:
    docker:
      - image: cimg/base:edge
    steps:
      - run: echo "<pre>hi from the artifact</pre>" > /tmp/artifact.html
      - store_artifacts:
          path: /tmp/artifact.html
          destination: artifact.html
      - run: echo $bar
      - run: echo $bar1

workflows:
  version: 2
  btd:
    jobs:
      - plsrun:
          context:
            - foo
            - foo2