version: 2
jobs:
  build:
    machine: true
    shell: sudo /bin/bash
    steps:
      - run: echo 'export PATH="$INSTALL_LOCATION/flutter/bin:$PATH"' >> "$BASH_ENV"
      - run: echo "foo"

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
