version: 2
jobs:
  build:
    machine: true
    steps:
      - run: echo "SUCCESS"

workflows:
  version: 2
  build:
    jobs:
      - build:
          type: approval
          context:
            - admin-only
