version: 2

jobs:
  gitcheck:
    docker:
      - image: circleci/ruby:2.3-slim
    steps:
      - checkout
      - run: echo 'git status'
  list:
    docker:
      - image: circleci/ruby:2.3-slim
    steps:
      - checkout
      - run: ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - gitcheck:
          filters:
            branches:
              only:
                - approval
#      - list:
#          filters:
#            branches:
#              only: 
#                - approval
