version: 2.0
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/php:7.3-cli
    parallelism: 1000
    steps:
      - run: sleep 35
      - run: echo "this has been a test of the emergency broadcast system"
