version: 2.0
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/golang:1.11.1
    steps:
      - run: touch ~/.gitconfig && sudo chmod a-w ~/.gitconfig
      - checkout
      - run: killall while

notify:
  webhooks:
    - url: https://www.example.com/circleci/notify
  branches:
    only:
      - /.*/
