version: 2.1
jobs:
  build:
    machine: true
    resource_class: ryanwohara/testing
    steps:
      - run: mkdir -p tmp/foo
      - run: echo "Hola, from Runner!"
workflows:
  version: 2
  btd:
    jobs:
      - build
