version: 2
jobs:
  plsrun:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - run: pip3 install requests
      - run:
          shell: /usr/bin/python3
          command: |
            import requests
            r = requests.get('https://api.github.com/events')
            print(r.text)
            print(r.text)
            print(r.text)
            print(r.text)
            print(r.text)
            print(r.text)
            print(r.text)
            print(r.text)
            print(r.text)

workflows:
  version: 2
  btd:
    jobs:
      - plsrun
