version: 2.1
jobs:
  build:
    docker:
      - image: circleci/circleci-cli:0.1.26646
    resource_class: ryanwohara/wsl
    steps:
      - run: echo $PATH
      - run: circleci version
      - run: circleci help
      - run: which circleci
      - run: which circleci-agent

workflows:
  btd:
    jobs:
      - build
