version: 2
jobs:
  build:
    machine:
      name: android/android-machine
    environment:
      INSTALL_LOCATION: /tmp
    steps:
      - run: |
          echo "export PATH=$INSTALL_LOCATION/flutter/bin:$PATH" >> "$BASH_ENV"
          source "$BASH_ENV"
      - run: echo "foo"
      
