version: 2.1
jobs:
  build:
    machine: true
    parallelism: 5
    resource_class: ryanwohara/testing
    steps:
      - run: echo "Hola, from Runner!"
      - run: whoami
workflows:
  version: 2
  btd:
    jobs:
      - build
