version: 2.1
jobs:
  build:
    docker:
      - image: circleci/circleci-cli:0.1.26646
    steps:
      - run: echo $PATH
      - run: circleci version
      - run: circleci help

workflows:
  btd:
    jobs:
      - build
