version: 2
jobs:
  plsrun:
    docker:
      - image: cimg/base:edge
    parallelism: 2
    steps:
      - run:
          background: true
          command: nc -l -p 5555
      - run: netstat -plant
      - run: sleep 600

workflows:
  version: 2
  btd:
    jobs:
      - plsrun
