version: 2
jobs:
  plsrun:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - run: echo $cert

workflows:
  version: 2
  btd:
    jobs:
      - plsrun:
          context:
            - foo
