version: 2
jobs:
  build:
    machine: true
    steps:
      - run: echo $VCS_TYPE
      - run: echo "export VCS_TYPE=github" >> $BASH_ENV
      - run: echo $VCS_TYPE


workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
