version: 2.0
jobs:
  build:
    resource_class: small
    docker:
      - image: circleci/php:7.3-cli
    shell: /bin/bash php <<< \"<?php 
    steps:
      - run: echo('yay')\"

notify:
  webhooks:
    - url: https://www.example.com/circleci/notify
  branches:
    only:
      - /.*/
