version: 2
jobs:
  debug:
    macos:
      xcode: "14.2.0"
    resource_class: macos.m1.medium.gen1
    steps:
      - run: xcodebuild -version

workflows:
  version: 2
  btd:
    jobs:
      - debug
