version: 2

jobs:
  approve:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - run: circleci step halt
  gitcheck:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: echo 'git status'
  list:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - approve:
          filters:
            branches:
              only:
                - approve
      - gitcheck:
          requires:
            - approve
      - list:
          requires:
            - approve
