version: 2
jobs:
  build:
    machine: true
    resource_class: ryanwohara/test
    steps:
      - run: mkdir -p /tmp/foo
      - run: echo "Hola, from Runner!" > /tmp/foo/output
      - persist_to_workspace:
          root: /tmp/foo
          paths: ouptut
      - run: rm -rf /tmp/foo
  test:
    machine: true
    resource_class: ryanwohara/test
    steps:
      - run: mkdir -p /tmp/foo
      - attach_workspace:
          at: /tmp/foo
      - run: cat /tmp/foo/output || cat /tmp/foo/foo/output
workflows:
  version: 2
  btd:
    jobs:
      - build
      - test:
          requires:
            - build
